### PR TITLE
Support NotEquals and NotContains

### PR DESCRIPTION
**Pull request by chriskuchin**
Needed NotContains for a few of my checks and Added NotEquals since it was a low overhead feature as well

Mimiced existing expectation tests to verify my logic

### CODE REVIEW

**Comment by chriskuchin** [comment]
@codingupastorm @stevensdavid Let me know if there is anything more you would like in the MR

**Review by stevensdavid — CHANGES_REQUESTED** [review]
Hi! Thank you for your contribution!

This looks really good! I love the idea of adding support for arbitrary additional tags for the metrics here and very much appreciate the overall clean-up work you've done adding units and descriptions to the existing metrics.

Do you mind updating the README, documenting:
- the new metric `status` under "Tracked metrics"
- the `tags` argument
- the new comparison operators

`tags` should maybe also be added to the `Step` struct in order to add support for tags on individual steps in a story 🤔 Really underlines that we should refactor probes/stories to share logic but that is definitely out-of-scope for this PR!

Thanks again! Once these things are addressed and I've had a play around with running it I'd love to get this merged!

**Comment by chriskuchin** [comment]
@stevensdavid Thanks! I actually hadn't intended to submit all those other changes but forgot how PRs work 😆 

So I added the unit to see how it worked and forgot about but it actually changes the metric name from `duration_buckets` to `duration_milliseconds_buckets`. Not sure how you feel about a backwards incompatible metric naming change. I went ahead and reverted but happy to add it back if you are ok with the metric change.

I missed that steps have their own attributes block so have added the story tags to that block now too. I struggled to see a use case for a tag field on the steps but definitely think the parent object tags should be there. Happy to make the change if you see a use for tags on steps.

I updated the readme as well. 

Let me know if you need anything else here.

**Comment by stevensdavid** [comment]
Hey again @chriskuchin ! I'm very sorry for slow responses, it's been a busy period for me. 

I think making backwards-incompatible naming changes of this nature is a good idea -- we're still in a 0.x stage and haven't made any guarantees that would be broken. Adding units is great, and should have been there from the start 😄 

I've tested things locally and it seems to work as it should, so I think once the units are back in I'd be happy to approve this. I'm not sure if @codingupastorm also wants to take a look, will message him!

**Comment by chriskuchin** [comment]
Ok cool added back the Unit. In case you didn't notice I made one other change to disable connection pooling as we had a failing http test because of that.

**Comment by stevensdavid** [comment]
I did see that! Seems like a reasonable addition to make. I'm happy with how things look now! Just going to wait for @codingupastorm 's input before we can merge this and draft a new release. Thank you Chris!

**Review by stevensdavid — APPROVED** [review]

**Comment by stevensdavid** [comment]
I merged and released this now! Thank you for your contributions @chriskuchin ! 🎉

**Pull request merged**
